---
- name: Ensure Docker, Minikube, and Kubernetes tools are installed and running
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    # --------------------- Docker ---------------------
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Fix Docker permissions (BuildKit lock)
      file:
        path: "/home/{{ ansible_user }}/.docker"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
        mode: '0755'


        # --------------------- Kubectl ---------------------
    - name: Check if kubectl is already installed
      stat:
        path: /usr/local/bin/kubectl
      register: kubectl_check

    - name: Download kubectl binary
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      when: not kubectl_check.stat.exists

    # --------------------- Minikube ---------------------
    - name: Check if Minikube is already installed
      stat:
        path: /usr/local/bin/minikube
      register: minikube_check

    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
      when: not minikube_check.stat.exists
    - name: Start Minikube with Docker driver
      become_user: "{{ ansible_user }}"
      shell: |
        minikube start --driver=docker
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"

