apiVersion: apps/v1
kind: Deployment
metadata:
  name: simon-game-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simon-game
  template:
    metadata:
      labels:
        app: simon-game
    spec:
      containers:
      - name: simon-game
        image: simon-game:v1      
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
